name: Build and Release Executable

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout le code source
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurer Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3. Installer les dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    # 4. Générer l'exécutable avec PyInstaller
    - name: Build executable
      run: |
        pyinstaller --windowed --clean telechargeur_gui.py

    # 5. Créer une Release GitHub
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.${{ github.run_number }}
        release_name: "Release v1.0.${{ github.run_number }}"
        body: |
          Nouveau build généré automatiquement.
          - **Version :** v1.0.${{ github.run_number }}
        draft: false
        prerelease: false

    # 6. Ajouter l'exécutable à la Release
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/telechargeur_gui.exe
        asset_name: telechargeur_gui.exe
        asset_content_type: application/octet-stream
